// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "InputMethodContext.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* InputMethodContext_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  InputMethodContext_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_InputMethodContext_2eproto() {
  protobuf_AddDesc_InputMethodContext_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "InputMethodContext.proto");
  GOOGLE_CHECK(file != NULL);
  InputMethodContext_descriptor_ = file->message_type(0);
  static const int InputMethodContext_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InputMethodContext, input_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InputMethodContext, pageindex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InputMethodContext, selectionindex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InputMethodContext, candidates_),
  };
  InputMethodContext_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      InputMethodContext_descriptor_,
      InputMethodContext::default_instance_,
      InputMethodContext_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InputMethodContext, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InputMethodContext, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(InputMethodContext));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_InputMethodContext_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    InputMethodContext_descriptor_, &InputMethodContext::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_InputMethodContext_2eproto() {
  delete InputMethodContext::default_instance_;
  delete InputMethodContext_reflection_;
}

void protobuf_AddDesc_InputMethodContext_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030InputMethodContext.proto\"b\n\022InputMetho"
    "dContext\022\r\n\005Input\030\001 \001(\t\022\021\n\tPageIndex\030\002 \001"
    "(\005\022\026\n\016SelectionIndex\030\003 \001(\005\022\022\n\nCandidates"
    "\030\004 \003(\t", 126);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "InputMethodContext.proto", &protobuf_RegisterTypes);
  InputMethodContext::default_instance_ = new InputMethodContext();
  InputMethodContext::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_InputMethodContext_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_InputMethodContext_2eproto {
  StaticDescriptorInitializer_InputMethodContext_2eproto() {
    protobuf_AddDesc_InputMethodContext_2eproto();
  }
} static_descriptor_initializer_InputMethodContext_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int InputMethodContext::kInputFieldNumber;
const int InputMethodContext::kPageIndexFieldNumber;
const int InputMethodContext::kSelectionIndexFieldNumber;
const int InputMethodContext::kCandidatesFieldNumber;
#endif  // !_MSC_VER

InputMethodContext::InputMethodContext()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void InputMethodContext::InitAsDefaultInstance() {
}

InputMethodContext::InputMethodContext(const InputMethodContext& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void InputMethodContext::SharedCtor() {
  _cached_size_ = 0;
  input_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  pageindex_ = 0;
  selectionindex_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

InputMethodContext::~InputMethodContext() {
  SharedDtor();
}

void InputMethodContext::SharedDtor() {
  if (input_ != &::google::protobuf::internal::kEmptyString) {
    delete input_;
  }
  if (this != default_instance_) {
  }
}

void InputMethodContext::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* InputMethodContext::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return InputMethodContext_descriptor_;
}

const InputMethodContext& InputMethodContext::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_InputMethodContext_2eproto();  return *default_instance_;
}

InputMethodContext* InputMethodContext::default_instance_ = NULL;

InputMethodContext* InputMethodContext::New() const {
  return new InputMethodContext;
}

void InputMethodContext::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_input()) {
      if (input_ != &::google::protobuf::internal::kEmptyString) {
        input_->clear();
      }
    }
    pageindex_ = 0;
    selectionindex_ = 0;
  }
  candidates_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool InputMethodContext::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string Input = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_input()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->input().data(), this->input().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_PageIndex;
        break;
      }
      
      // optional int32 PageIndex = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_PageIndex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pageindex_)));
          set_has_pageindex();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_SelectionIndex;
        break;
      }
      
      // optional int32 SelectionIndex = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_SelectionIndex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &selectionindex_)));
          set_has_selectionindex();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_Candidates;
        break;
      }
      
      // repeated string Candidates = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Candidates:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_candidates()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->candidates(0).data(), this->candidates(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_Candidates;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void InputMethodContext::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string Input = 1;
  if (has_input()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->input().data(), this->input().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->input(), output);
  }
  
  // optional int32 PageIndex = 2;
  if (has_pageindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->pageindex(), output);
  }
  
  // optional int32 SelectionIndex = 3;
  if (has_selectionindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->selectionindex(), output);
  }
  
  // repeated string Candidates = 4;
  for (int i = 0; i < this->candidates_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->candidates(i).data(), this->candidates(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->candidates(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* InputMethodContext::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string Input = 1;
  if (has_input()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->input().data(), this->input().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->input(), target);
  }
  
  // optional int32 PageIndex = 2;
  if (has_pageindex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->pageindex(), target);
  }
  
  // optional int32 SelectionIndex = 3;
  if (has_selectionindex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->selectionindex(), target);
  }
  
  // repeated string Candidates = 4;
  for (int i = 0; i < this->candidates_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->candidates(i).data(), this->candidates(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->candidates(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int InputMethodContext::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string Input = 1;
    if (has_input()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->input());
    }
    
    // optional int32 PageIndex = 2;
    if (has_pageindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->pageindex());
    }
    
    // optional int32 SelectionIndex = 3;
    if (has_selectionindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->selectionindex());
    }
    
  }
  // repeated string Candidates = 4;
  total_size += 1 * this->candidates_size();
  for (int i = 0; i < this->candidates_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->candidates(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void InputMethodContext::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const InputMethodContext* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const InputMethodContext*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void InputMethodContext::MergeFrom(const InputMethodContext& from) {
  GOOGLE_CHECK_NE(&from, this);
  candidates_.MergeFrom(from.candidates_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_input()) {
      set_input(from.input());
    }
    if (from.has_pageindex()) {
      set_pageindex(from.pageindex());
    }
    if (from.has_selectionindex()) {
      set_selectionindex(from.selectionindex());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void InputMethodContext::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InputMethodContext::CopyFrom(const InputMethodContext& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InputMethodContext::IsInitialized() const {
  
  return true;
}

void InputMethodContext::Swap(InputMethodContext* other) {
  if (other != this) {
    std::swap(input_, other->input_);
    std::swap(pageindex_, other->pageindex_);
    std::swap(selectionindex_, other->selectionindex_);
    candidates_.Swap(&other->candidates_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata InputMethodContext::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = InputMethodContext_descriptor_;
  metadata.reflection = InputMethodContext_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
