// Generated by ProtoGen, Version=2.3.0.277, Culture=neutral, PublicKeyToken=8fd7408b07f8d2cd.  DO NOT EDIT!

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Proto {
  
  public static partial class InputMethodContext {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_InputMethodContext__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::InputMethodContext, global::InputMethodContext.Builder> internal__static_InputMethodContext__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static InputMethodContext() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "ChhJbnB1dE1ldGhvZENvbnRleHQucHJvdG8iYgoSSW5wdXRNZXRob2RDb250" + 
          "ZXh0Eg0KBUlucHV0GAEgASgJEhEKCVBhZ2VJbmRleBgCIAEoBRIWCg5TZWxl" + 
          "Y3Rpb25JbmRleBgDIAEoBRISCgpDYW5kaWRhdGVzGAQgAygJ");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_InputMethodContext__Descriptor = Descriptor.MessageTypes[0];
        internal__static_InputMethodContext__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::InputMethodContext, global::InputMethodContext.Builder>(internal__static_InputMethodContext__Descriptor,
                new string[] { "Input", "PageIndex", "SelectionIndex", "Candidates", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
}
#region Messages
public sealed partial class InputMethodContext : pb::GeneratedMessage<InputMethodContext, InputMethodContext.Builder> {
  private static readonly InputMethodContext defaultInstance = new Builder().BuildPartial();
  public static InputMethodContext DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override InputMethodContext DefaultInstanceForType {
    get { return defaultInstance; }
  }
  
  protected override InputMethodContext ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::Proto.InputMethodContext.internal__static_InputMethodContext__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<InputMethodContext, InputMethodContext.Builder> InternalFieldAccessors {
    get { return global::Proto.InputMethodContext.internal__static_InputMethodContext__FieldAccessorTable; }
  }
  
  public const int InputFieldNumber = 1;
  private bool hasInput;
  private string input_ = "";
  public bool HasInput {
    get { return hasInput; }
  }
  public string Input {
    get { return input_; }
  }
  
  public const int PageIndexFieldNumber = 2;
  private bool hasPageIndex;
  private int pageIndex_ = 0;
  public bool HasPageIndex {
    get { return hasPageIndex; }
  }
  public int PageIndex {
    get { return pageIndex_; }
  }
  
  public const int SelectionIndexFieldNumber = 3;
  private bool hasSelectionIndex;
  private int selectionIndex_ = 0;
  public bool HasSelectionIndex {
    get { return hasSelectionIndex; }
  }
  public int SelectionIndex {
    get { return selectionIndex_; }
  }
  
  public const int CandidatesFieldNumber = 4;
  private pbc::PopsicleList<string> candidates_ = new pbc::PopsicleList<string>();
  public scg::IList<string> CandidatesList {
    get { return pbc::Lists.AsReadOnly(candidates_); }
  }
  public int CandidatesCount {
    get { return candidates_.Count; }
  }
  public string GetCandidates(int index) {
    return candidates_[index];
  }
  
  public override bool IsInitialized {
    get {
      return true;
    }
  }
  
  public override void WriteTo(pb::CodedOutputStream output) {
    int size = SerializedSize;
    if (HasInput) {
      output.WriteString(1, Input);
    }
    if (HasPageIndex) {
      output.WriteInt32(2, PageIndex);
    }
    if (HasSelectionIndex) {
      output.WriteInt32(3, SelectionIndex);
    }
    if (candidates_.Count > 0) {
      foreach (string element in candidates_) {
        output.WriteString(4, element);
      }
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (HasInput) {
        size += pb::CodedOutputStream.ComputeStringSize(1, Input);
      }
      if (HasPageIndex) {
        size += pb::CodedOutputStream.ComputeInt32Size(2, PageIndex);
      }
      if (HasSelectionIndex) {
        size += pb::CodedOutputStream.ComputeInt32Size(3, SelectionIndex);
      }
      {
        int dataSize = 0;
        foreach (string element in CandidatesList) {
          dataSize += pb::CodedOutputStream.ComputeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * candidates_.Count;
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static InputMethodContext ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static InputMethodContext ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static InputMethodContext ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static InputMethodContext ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static InputMethodContext ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static InputMethodContext ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static InputMethodContext ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static InputMethodContext ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static InputMethodContext ParseFrom(pb::CodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static InputMethodContext ParseFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(InputMethodContext prototype) {
    return (Builder) new Builder().MergeFrom(prototype);
  }
  
  public sealed partial class Builder : pb::GeneratedBuilder<InputMethodContext, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {}
    
    InputMethodContext result = new InputMethodContext();
    
    protected override InputMethodContext MessageBeingBuilt {
      get { return result; }
    }
    
    public override Builder Clear() {
      result = new InputMethodContext();
      return this;
    }
    
    public override Builder Clone() {
      return new Builder().MergeFrom(result);
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::InputMethodContext.Descriptor; }
    }
    
    public override InputMethodContext DefaultInstanceForType {
      get { return global::InputMethodContext.DefaultInstance; }
    }
    
    public override InputMethodContext BuildPartial() {
      if (result == null) {
        throw new global::System.InvalidOperationException("build() has already been called on this Builder");
      }
      result.candidates_.MakeReadOnly();
      InputMethodContext returnMe = result;
      result = null;
      return returnMe;
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is InputMethodContext) {
        return MergeFrom((InputMethodContext) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(InputMethodContext other) {
      if (other == global::InputMethodContext.DefaultInstance) return this;
      if (other.HasInput) {
        Input = other.Input;
      }
      if (other.HasPageIndex) {
        PageIndex = other.PageIndex;
      }
      if (other.HasSelectionIndex) {
        SelectionIndex = other.SelectionIndex;
      }
      if (other.candidates_.Count != 0) {
        base.AddRange(other.candidates_, result.candidates_);
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::CodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      pb::UnknownFieldSet.Builder unknownFields = null;
      while (true) {
        uint tag = input.ReadTag();
        switch (tag) {
          case 0: {
            if (unknownFields != null) {
              this.UnknownFields = unknownFields.Build();
            }
            return this;
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag);
            break;
          }
          case 10: {
            Input = input.ReadString();
            break;
          }
          case 16: {
            PageIndex = input.ReadInt32();
            break;
          }
          case 24: {
            SelectionIndex = input.ReadInt32();
            break;
          }
          case 34: {
            AddCandidates(input.ReadString());
            break;
          }
        }
      }
    }
    
    
    public bool HasInput {
      get { return result.HasInput; }
    }
    public string Input {
      get { return result.Input; }
      set { SetInput(value); }
    }
    public Builder SetInput(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      result.hasInput = true;
      result.input_ = value;
      return this;
    }
    public Builder ClearInput() {
      result.hasInput = false;
      result.input_ = "";
      return this;
    }
    
    public bool HasPageIndex {
      get { return result.HasPageIndex; }
    }
    public int PageIndex {
      get { return result.PageIndex; }
      set { SetPageIndex(value); }
    }
    public Builder SetPageIndex(int value) {
      result.hasPageIndex = true;
      result.pageIndex_ = value;
      return this;
    }
    public Builder ClearPageIndex() {
      result.hasPageIndex = false;
      result.pageIndex_ = 0;
      return this;
    }
    
    public bool HasSelectionIndex {
      get { return result.HasSelectionIndex; }
    }
    public int SelectionIndex {
      get { return result.SelectionIndex; }
      set { SetSelectionIndex(value); }
    }
    public Builder SetSelectionIndex(int value) {
      result.hasSelectionIndex = true;
      result.selectionIndex_ = value;
      return this;
    }
    public Builder ClearSelectionIndex() {
      result.hasSelectionIndex = false;
      result.selectionIndex_ = 0;
      return this;
    }
    
    public pbc::IPopsicleList<string> CandidatesList {
      get { return result.candidates_; }
    }
    public int CandidatesCount {
      get { return result.CandidatesCount; }
    }
    public string GetCandidates(int index) {
      return result.GetCandidates(index);
    }
    public Builder SetCandidates(int index, string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      result.candidates_[index] = value;
      return this;
    }
    public Builder AddCandidates(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      result.candidates_.Add(value);
      return this;
    }
    public Builder AddRangeCandidates(scg::IEnumerable<string> values) {
      base.AddRange(values, result.candidates_);
      return this;
    }
    public Builder ClearCandidates() {
      result.candidates_.Clear();
      return this;
    }
  }
  static InputMethodContext() {
    object.ReferenceEquals(global::Proto.InputMethodContext.Descriptor, null);
  }
}

#endregion

